In [ ]:
import numpy as np
from collections import defaultdict as dd
from typing import List, Dict, Set
import nltk
from tqdm import tqdm_notebook, tnrange
import pickle
from termcolor import colored
import sqlite3

In [ ]:
import collections

class OrderedSet(collections.MutableSet):

    def __init__(self, iterable=None):
        self.end = end = [] 
        end += [None, end, end]         # sentinel node for doubly linked list
        self.map = {}                   # key --> [key, prev, next]
        if iterable is not None:
            self |= iterable

    def __len__(self):
        return len(self.map)

    def __contains__(self, key):
        return key in self.map

    def add(self, key):
        if key not in self.map:
            end = self.end
            curr = end[1]
            curr[2] = end[1] = self.map[key] = [key, curr, end]

    def discard(self, key):
        if key in self.map:        
            key, prev, next = self.map.pop(key)
            prev[2] = next
            next[1] = prev

    def __iter__(self):
        end = self.end
        curr = end[2]
        while curr is not end:
            yield curr[0]
            curr = curr[2]

    def __reversed__(self):
        end = self.end
        curr = end[1]
        while curr is not end:
            yield curr[0]
            curr = curr[1]

    def pop(self, last=True):
        if not self:
            raise KeyError('set is empty')
        key = self.end[1][0] if last else self.end[2][0]
        self.discard(key)
        return key

    def __repr__(self):
        if not self:
            return '%s()' % (self.__class__.__name__,)
        return '%s(%r)' % (self.__class__.__name__, list(self))

    def __eq__(self, other):
        if isinstance(other, OrderedSet):
            return len(self) == len(other) and list(self) == list(other)
        return set(self) == set(other)

In [ ]:
conn = sqlite3.connect("Dane/wikipedyjka2.db")

In [ ]:
def to_lemma_mapping():
    all_lemmas = dd(list)
    for line in open('Dane/polimorfologik-2.1.txt', encoding='utf-8'):
        L = line.split(';')[:2]
        all_lemmas[L[1].lower()].append(L[0].lower())
    return all_lemmas
lemma_mapping = to_lemma_mapping()

In [54]:
wiki_list = []
key = ""
with open("Dane/fp_wiki.txt") as f:
    cntr = -1
    for line in f:
        tokenized_line = line.split(": ")
        if tokenized_line[0] == "TITLE":
            if tokenized_line[-1][-1] == "\n":
                tokenized_line[-1] = tokenized_line[-1][:-1]
            cntr+=1
            wiki_list.append((tokenized_line[-1], []))
            continue
        wiki_list[-1][1].append(line)

In [55]:
cntr1 = 0
title_positional_index = dd(list)
article_positional_index = dd(list)
title_lemma_positional_index = dd(list)
article_lemma_positional_index = dd(list)

for title, article in wiki_list:
    tokenized_line = nltk.word_tokenize(title)
    cntr2 = 0
    for w in tokenized_line:
        w = w.lower()
        title_positional_index[w].append((cntr1, cntr2))
        for lemma in lemma_mapping[w]:
            title_lemma_positional_index[lemma].append((cntr1, cntr2))
        cntr2 +=1
    cntr2 = 0
    for line in article:
        tokenized_line = nltk.word_tokenize(line)
        for w in tokenized_line:
            w = w.lower()
            article_positional_index[w].append((cntr1, cntr2))
            for lemma in lemma_mapping[w]:
                article_lemma_positional_index[lemma].append((cntr1, cntr2))
            cntr2 += 1
    cntr1 += 1

In [ ]:
c = conn.cursor()
for k, v in title_positional_index.items():
    if not k.isalnum():
        continue
    try:
        c.execute(f'''DROP TABLE IF EXISTS tab_{k}_title''')
        c.execute(f'''CREATE TABLE tab_{k}_title
             (title_position INTEGER, word_position INTEGER)''')
        for ind in v:
            c.execute(f"INSERT INTO tab_{k}_title VALUES ({ind[0]}, {ind[1]})")
    except:
        pass
conn.commit()
for k, v in article_positional_index:
    if not k.isalnum():
        continue
    try:
        c.execute(f'''DROP TABLE IF EXISTS tab_{k}_article''')
        c.execute(f'''CREATE TABLE tab_{k}_article
                 (title_position INTEGER, word_position INTEGER)''')
        for ind in v:
            c.execute(f"INSERT INTO tab_{k}_article VALUES ({ind[0]}, {ind[1]})")
    except:
        pass
conn.commit()
for k, v in title_lemma_positional_index:
    if not k.isalnum():
        continue
    try:
        c.execute(f'''DROP TABLE IF EXISTS tab_{k}_lemma_title''')
        c.execute(f'''CREATE TABLE tab_{k}_lemma_title
                 (title_position INTEGER, word_position INTEGER)''')
        for ind in v:
            c.execute(f"INSERT INTO tab_{k}_lemma_title VALUES ({ind[0]}, {ind[1]})")
    except:
        pass
conn.commit()
for k, v in article_lemma_positional_index:
    if not k.isalnum():
        continue
    try:
        c.execute(f'''DROP TABLE IF EXISTS tab_{k}_lemma_article''')
        c.execute(f'''CREATE TABLE tab_{k}_lemma_article
                 (title_position INTEGER, word_position INTEGER)''')
        for ind in v:
            c.execute(f"INSERT INTO tab_{k}_lemma_article VALUES ({ind[0]}, {ind[1]})")
    except:
        pass
conn.commit()

In [ ]:
conn.commit()

In [65]:
print(k)

11

In [ ]:
def word_query_alt(w):
    w = w.lower()
    res = [OrderedSet(), OrderedSet(), OrderedSet(), OrderedSet()]
    try:
        for el in title_positional_index[w]:
            res[0].add(el[0])
    except:
        pass
    try:
        for el in article_positional_index[w]:
            res[1].add(el[0])
    except:
        pass
    for lemma in lemma_mapping[w]:
        try:
            for el in title_lemma_positional_index[w]:
                res[2].add(el[0])
        except:
            pass
        try:
            for el in article_lemma_positional_index[w]:
                res[3].add(el[0])
        except:
            pass
    res[1] |= res[0]
    res[2] |= res[1]
    res[3] |= res[2]

#     print(res)
    return res

In [89]:
def word_query(w):
    w = w.lower()
    res = [OrderedSet(), OrderedSet(), OrderedSet(), OrderedSet()]
    try:
        for el in c.execute(f'SELECT * FROM tab_{w}_title'):
            res[0].add(el[0])
    except:
        pass
    try:
        for el in c.execute(f'SELECT * FROM tab_{w}_article'):
            res[1].add(el[0])
    except:
        pass
    for lemma in lemma_mapping[w]:
        try:
            for el in c.execute(f'SELECT * FROM tab_{lemma}_lemma_title'):
                res[2].add(el[0])
        except:
            pass
        try:
            for el in c.execute(f'SELECT * FROM tab_{lemma}_lemma_article'):
                res[3].add(el[0])
        except:
            pass
    res[1] |= res[0]
    res[2] |= res[1]
    res[3] |= res[2]

#     print(res)
    return res

In [90]:
def phrase_word_query(w, i):
    w = w.lower()
    res = [OrderedSet(), OrderedSet(), OrderedSet(), OrderedSet()]
    try:
        for el in c.execute(f'SELECT * FROM tab_{w}_title'):
            res[0].add((el[0], el[1] - i))
    except:
        pass
    try:
        for el in c.execute(f'SELECT * FROM tab_{w}_article'):
            res[1].add((el[0], el[1] - i))
    except:
        pass
    for lemma in lemma_mapping[w]:
        try:
            for el in c.execute(f'SELECT * FROM tab_{lemma}_lemma_title'):
                res[2].add((el[0], el[1] - i))
        except:
            pass
        try:
            for el in c.execute(f'SELECT * FROM tab_{lemma}_lemma_article'):
                res[3].add((el[0], el[1] - i))
        except:
            pass
    res[1] |= res[0]
    res[2] |= res[1]
    res[3] |= res[2]
    return res

In [ ]:
def phrase_word_query_alt(w, i):
    w = w.lower()
    res = [OrderedSet(), OrderedSet(), OrderedSet(), OrderedSet()]
    try:
        for el in title_positional_index[w]:
            res[0].add((el[0], el[1] - i))
    except:
        pass
    try:
        for el in article_positional_index[w]:
            res[1].add((el[0], el[1] - i))
    except:
        pass
    for lemma in lemma_mapping[w]:
        try:
            for el in title_lemma_positional_index[w]:
                res[2].add((el[0], el[1] - i))
        except:
            pass
        try:
            for el in article_lemma_positional_index[w]:
                res[3].add((el[0], el[1] - i))
        except:
            pass
    res[1] |= res[0]
    res[2] |= res[1]
    res[3] |= res[2]
    return res

In [91]:
def query(words):
    res = [OrderedSet(), OrderedSet(), OrderedSet(), OrderedSet()]
    for i, w in enumerate(words):
        w = w.lower()
        if i == 0:
            res1 = word_query(w)
            for j in range(4):
                res[j] |= res1[j]
            continue
        res1 = word_query(w)
        for j in range(4):
            res[j] &= res1[j]
    res = phrase_query(words) + res
    for i in range(1,8):
        for j in range(i):
            res[i] -= res[j]
    return res

In [92]:
def phrase_query(words):
    res = [OrderedSet(), OrderedSet(), OrderedSet(), OrderedSet()]
    for i, w in enumerate(words):
        w = w.lower()
        if i == 0:
            res1 = phrase_word_query(w, i)
            for j in range(4):
                res[j] |= res1[j]
            continue
        res1 = phrase_word_query(w, i)
        for j in range(4):
            res[j] &= res1[j]
    res1 = res
    res = [OrderedSet(), OrderedSet(), OrderedSet(), OrderedSet()]
    for i in range(4):
        for el in res1[i]:
            res[i].add(el[0])
    res[1] -= res[0]
    res[2] -= res[0] | res[1]
    res[3] -= res[0] | res[1] | res[2]
    return res

In [93]:
def to_lemmas(tokens):
    res = []
    for t in tokens:
        t = t.lower()
        res.append(t)
        res += lemma_mapping[t]
    return res

def in_lemmas(w, lemmas):
    w = w.lower()
    if w in lemmas:
        return True
    for l in lemma_mapping[w]:
        if l in lemmas:
            return True
    return False


def search_and_print(words):
    is_phrase = words[0] == "\""
    if is_phrase:
        words = words[1:-1]
    tokens = [t.lower() for t in nltk.word_tokenize(words)]
    article_sets = phrase_query(tokens) if is_phrase else query(tokens)
    lemmas = to_lemmas(tokens)
    for articles in article_sets:
        for el in articles:
            title, article = wiki_list[el]
            for w in nltk.word_tokenize(title):
                if in_lemmas(w, lemmas):
                    print(colored(w, "green"), end=" ")
                else:
                    print(w, end=" ")
            print("\n")
            for line in article:
                for w in nltk.word_tokenize(line):
                    if in_lemmas(w, lemmas):
                        print(colored(w, "green"), end=" ")
                    else:
                        print(w, end=" ")
                print("")
            print("")

In [88]:
print(phrase_query(["gdzie", "spadają", "anioły"]))

[OrderedSet([142904, 144706, 217530, 224912, 225556, 232112, 241795, 264899, 297171, 312466, 322199, 344328, 352551, 364502, 366502, 431377, 443190, 444386, 454455, 456995, 457557, 479521, 497695, 504927, 532489, 535170, 567409, 580103, 589441, 593781, 598143, 626817, 627196, 628082, 628902, 637343, 646220, 674781, 693514, 709152, 717983, 757099, 797260, 797970, 801165, 803027, 810814, 813638, 840147, 856247, 897691, 903595, 917405, 987861, 996769, 1006809, 1006825, 1043201, 1045513, 1057625, 1063380, 1074372, 1157406, 1166427]), OrderedSet(), OrderedSet(), OrderedSet()]

In [102]:
search_and_print("doroty terakowskiej")

In [106]:
phrase_word_query("doroty", 0)[1]

OrderedSet([(138801, 7), (218403, 3), (235461, 2), (236277, 3), (283884, 1), (389343, 3), (437310, 3), (440105, 3), (614850, 3), (634595, 3), (636835, 3), (640710, 7), (649709, 3), (652408, 3), (665922, 3), (668221, 3), (669730, 7), (710052, 3), (713852, 3), (716236, 3), (731481, 3), (741762, 3), (751005, 7), (760171, 3), (813581, 2), (816782, 5), (873831, 3), (874840, 3), (897133, 3), (914564, 3), (923389, 3), (928653, 3), (944005, 3), (947024, 5), (993638, 3), (997309, 3), (1001749, 3), (1005370, 3), (1049294, 3), (1077587, 3), (1080463, 3), (1092081, 3), (1170911, 3), (1172584, 3), (1172737, 4), (1195907, 3), (1205204, 8)])

In [107]:
phrase_word_query("doroty", 0)[0]

OrderedSet([(138801, 7), (218403, 3), (235461, 2), (236277, 3), (283884, 1), (389343, 3), (437310, 3), (440105, 3), (614850, 3), (634595, 3), (636835, 3), (640710, 7), (649709, 3), (652408, 3), (665922, 3), (668221, 3), (669730, 7), (710052, 3), (713852, 3), (716236, 3), (731481, 3), (741762, 3), (751005, 7), (760171, 3), (813581, 2), (816782, 5), (873831, 3), (874840, 3), (897133, 3), (914564, 3), (923389, 3), (928653, 3), (944005, 3), (947024, 5), (993638, 3), (997309, 3), (1001749, 3), (1005370, 3), (1049294, 3), (1077587, 3), (1080463, 3), (1092081, 3), (1170911, 3), (1172584, 3), (1172737, 4), (1195907, 3), (1205204, 8)])

In [ ]:
c.execute(f'SELECT * FROM {"doroty"}_article')

In [110]:
article_positional_index["doroty"]

[(7392, 77),
 (12368, 112),
 (21125, 104),
 (22443, 52),
 (23289, 30),
 (24174, 85),
 (27537, 67),
 (33858, 84),
 (36959, 150),
 (37605, 48),
 (45237, 37),
 (47392, 111),
 (48213, 66),
 (51285, 24),
 (51481, 40),
 (51674, 97),
 (55761, 85),
 (55924, 59),
 (57459, 210),
 (57843, 46),
 (58951, 183),
 (59650, 63),
 (59890, 60),
 (61842, 15),
 (64400, 85),
 (64400, 113),
 (64403, 118),
 (64502, 86),
 (67888, 45),
 (68153, 71),
 (68153, 100),
 (70007, 125),
 (71169, 100),
 (76959, 70),
 (77739, 54),
 (79195, 169),
 (95885, 120),
 (116538, 36),
 (135752, 80),
 (136598, 244),
 (136604, 53),
 (136604, 82),
 (138801, 7),
 (138801, 23),
 (143464, 85),
 (149149, 48),
 (155462, 26),
 (156426, 30),
 (157819, 132),
 (158026, 29),
 (158526, 32),
 (162944, 41),
 (170888, 75),
 (171919, 42),
 (174801, 38),
 (180102, 105),
 (183428, 99),
 (184682, 141),
 (188887, 116),
 (193103, 81),
 (195890, 18),
 (195890, 72),
 (196478, 33),
 (199528, 165),
 (200879, 309),
 (203692, 41),
 (206152, 41),
 (208727, 99),
 (211816, 52),
 (215044, 60),
 (218403, 3),
 (218403, 9),
 (220228, 33),
 (221304, 120),
 (221304, 156),
 (226016, 127),
 (227201, 162),
 (230906, 31),
 (232613, 89),
 (235461, 2),
 (235461, 5),
 (235461, 9),
 (235461, 42),
 (236274, 98),
 (236277, 3),
 (236277, 12),
 (236277, 22),
 (236277, 96),
 (236277, 135),
 (239344, 23),
 (245264, 68),
 (247450, 59),
 (248126, 57),
 (250888, 94),
 (264899, 10),
 (267062, 59),
 (273826, 36),
 (274639, 54),
 (276516, 28),
 (277065, 47),
 (283217, 50),
 (283884, 1),
 (283884, 4),
 (284373, 84),
 (287679, 112),
 (290369, 13),
 (290912, 49),
 (294905, 50),
 (294911, 45),
 (298327, 54),
 (299347, 79),
 (304545, 104),
 (305899, 117),
 (307375, 24),
 (309078, 49),
 (309084, 30),
 (309094, 33),
 (312868, 95),
 (312968, 30),
 (316507, 42),
 (316672, 54),
 (316908, 58),
 (326284, 54),
 (326400, 127),
 (327030, 202),
 (332941, 42),
 (333473, 68),
 (335017, 92),
 (335025, 66),
 (336754, 60),
 (336823, 50),
 (337572, 146),
 (338395, 35),
 (343598, 47),
 (344523, 36),
 (344734, 51),
 (350005, 40),
 (350005, 96),
 (352468, 35),
 (364485, 58),
 (368505, 35),
 (370743, 46),
 (373943, 48),
 (380463, 43),
 (389343, 3),
 (389343, 9),
 (393281, 38),
 (393285, 39),
 (393691, 19),
 (393784, 35),
 (393789, 37),
 (398674, 38),
 (398799, 84),
 (399038, 40),
 (399843, 43),
 (399843, 55),
 (399848, 35),
 (403611, 55),
 (403684, 42),
 (404411, 54),
 (404617, 64),
 (404646, 43),
 (404804, 55),
 (406381, 43),
 (408268, 86),
 (410031, 74),
 (410034, 83),
 (413717, 145),
 (416572, 47),
 (424500, 46),
 (424931, 48),
 (425830, 149),
 (425848, 101),
 (428765, 34),
 (429960, 13),
 (434453, 88),
 (434804, 81),
 (437310, 3),
 (437310, 9),
 (437490, 69),
 (440105, 3),
 (440105, 9),
 (440105, 26),
 (443677, 47),
 (446094, 48),
 (446737, 43),
 (462614, 46),
 (465512, 86),
 (466823, 147),
 (475895, 57),
 (476951, 139),
 (478228, 37),
 (479469, 58),
 (487796, 123),
 (488442, 93),
 (488442, 104),
 (492175, 97),
 (493554, 36),
 (504650, 76),
 (506643, 74),
 (509129, 50),
 (511220, 50),
 (511761, 15),
 (517134, 28),
 (517140, 34),
 (517455, 78),
 (522600, 152),
 (526334, 43),
 (527249, 108),
 (533327, 69),
 (536103, 52),
 (536538, 40),
 (536538, 98),
 (547712, 18),
 (551399, 50),
 (557216, 31),
 (559774, 37),
 (561760, 15),
 (564838, 63),
 (572834, 50),
 (573080, 36),
 (573081, 79),
 (573663, 36),
 (573664, 36),
 (580047, 12),
 (587597, 38),
 (589896, 88),
 (592000, 17),
 (592909, 82),
 (593233, 21),
 (593774, 11),
 (598933, 64),
 (600568, 42),
 (601835, 96),
 (608433, 62),
 (609877, 22),
 (611614, 53),
 (611614, 244),
 (614850, 3),
 (614850, 9),
 (617495, 56),
 (621005, 40),
 (624514, 46),
 (624514, 81),
 (625866, 62),
 (633738, 90),
 (634595, 3),
 (634595, 8),
 (636835, 3),
 (636835, 8),
 (640710, 7),
 (640710, 18),
 (640710, 47),
 (644063, 97),
 (646712, 26),
 (646855, 26),
 (646863, 29),
 (647428, 33),
 (649709, 3),
 (649709, 10),
 (650669, 34),
 (652408, 3),
 (652408, 10),
 (652408, 93),
 (652552, 21),
 (652552, 103),
 (655481, 27),
 (659781, 45),
 (662100, 49),
 (664360, 43),
 (664724, 37),
 (664910, 50),
 (664910, 96),
 (665922, 3),
 (665922, 11),
 (668221, 3),
 (668221, 15),
 (669730, 7),
 (669730, 19),
 (687668, 80),
 (698830, 39),
 (699784, 15),
 (701684, 17),
 (704281, 23),
 (704281, 137),
 (705274, 15),
 (706052, 94),
 (706052, 183),
 (707757, 72),
 (710052, 3),
 (710052, 8),
 (713852, 3),
 (713852, 9),
 (716236, 3),
 (716236, 9),
 (720073, 77),
 (721898, 44),
 (722347, 32),
 (731481, 3),
 (731481, 12),
 (732430, 50),
 (736113, 34),
 (736118, 34),
 (739795, 58),
 (741762, 3),
 (741762, 8),
 (741762, 94),
 (741775, 66),
 (742131, 152),
 (744122, 99),
 (747619, 59),
 (751005, 7),
 (751005, 15),
 (751973, 39),
 (752755, 25),
 (754249, 25),
 (754249, 76),
 (754917, 48),
 (759001, 57),
 (760171, 3),
 (760171, 10),
 (760844, 133),
 (762755, 100),
 (762947, 34),
 (763009, 71),
 (765285, 22),
 (766946, 23),
 (770472, 32),
 (770862, 57),
 (780311, 24),
 (782226, 70),
 (785092, 41),
 (790854, 72),
 (793434, 53),
 (793443, 81),
 (793498, 38),
 (793529, 38),
 (793574, 42),
 (794898, 47),
 (795149, 52),
 (804169, 34),
 (804278, 33),
 (806857, 96),
 (813581, 2),
 (813581, 7),
 (814082, 132),
 (816782, 5),
 (816782, 11),
 (821358, 42),
 (821500, 93),
 (824593, 40),
 (829293, 62),
 (829293, 124),
 (845399, 44),
 (856986, 62),
 (863553, 110),
 (863553, 116),
 (865176, 8),
 (865694, 90),
 (866519, 50),
 (867306, 64),
 (867383, 235),
 (868590, 48),
 (870275, 51),
 (873831, 3),
 (873831, 8),
 (873831, 65),
 (873953, 72),
 (874840, 3),
 (874840, 8),
 (875895, 47),
 (881503, 57),
 (883437, 7),
 (884515, 64),
 (885239, 71),
 (891161, 15),
 (891161, 151),
 (892493, 34),
 (892856, 143),
 (897133, 3),
 (897133, 11),
 (897197, 39),
 (897776, 49),
 (904044, 56),
 (905768, 87),
 (907863, 43),
 (912157, 131),
 (914564, 3),
 (914564, 7),
 (914564, 12),
 (914564, 18),
 (914564, 71),
 (916827, 10),
 (920568, 31),
 (920979, 12),
 (921123, 62),
 (923389, 3),
 (923389, 10),
 (923389, 80),
 (928653, 3),
 (928653, 10),
 (928806, 16),
 (935155, 56),
 (935986, 88),
 (944005, 3),
 (944005, 9),
 (947024, 5),
 (947024, 14),
 (950609, 59),
 (951949, 109),
 (953528, 51),
 (953704, 37),
 (953976, 33),
 (953976, 77),
 (953976, 109),
 (954793, 41),
 (955708, 35),
 (959031, 86),
 (964911, 39),
 (974416, 52),
 (977036, 54),
 (978820, 67),
 (982784, 66),
 (983106, 53),
 (993638, 3),
 (993638, 9),
 (993638, 27),
 (994926, 88),
 (997309, 3),
 (997309, 16),
 (998467, 47),
 (1001749, 3),
 (1001749, 15),
 (1005171, 49),
 (1005370, 3),
 (1005370, 10),
 (1011508, 43),
 (1014094, 36),
 (1014414, 7),
 (1014762, 37),
 (1015919, 50),
 (1022736, 37),
 (1023790, 41),
 (1025001, 63),
 (1026392, 88),
 (1026793, 47),
 (1026793, 59),
 (1026923, 88),
 (1037804, 28),
 (1040997, 64),
 (1041021, 23),
 (1041021, 148),
 (1041021, 156),
 (1042817, 37),
 (1046928, 39),
 (1049294, 3),
 (1049294, 8),
 (1056485, 149),
 (1060160, 35),
 (1070295, 37),
 (1071578, 69),
 (1077587, 3),
 (1077587, 8),
 (1079754, 48),
 (1080463, 3),
 (1080463, 13),
 (1082253, 81),
 (1085002, 95),
 (1092081, 3),
 (1092081, 9),
 (1092081, 44),
 (1092081, 64),
 (1093046, 79),
 (1099993, 31),
 (1099993, 109),
 (1099993, 129),
 (1099993, 194),
 (1104876, 42),
 (1105961, 26),
 (1106699, 28),
 (1110685, 84),
 (1112501, 57),
 (1113726, 125),
 (1121944, 100),
 (1130171, 77),
 (1131481, 32),
 (1134120, 6),
 (1136401, 30),
 (1136692, 39),
 (1140154, 22),
 (1140828, 149),
 (1149777, 44),
 (1150315, 135),
 (1156442, 46),
 (1156677, 48),
 (1156988, 45),
 (1157582, 46),
 (1158406, 130),
 (1170911, 3),
 (1170911, 8),
 (1170911, 42),
 (1170949, 20),
 (1172572, 34),
 (1172584, 3),
 (1172584, 14),
 (1172588, 19),
 (1172737, 4),
 (1172737, 15),
 (1177785, 54),
 (1178137, 33),
 (1179077, 40),
 (1190402, 16),
 (1194826, 45),
 (1195501, 115),
 (1195907, 3),
 (1195907, 9),
 (1195907, 58),
 (1196383, 180),
 (1197291, 56),
 (1205204, 8),
 (1205204, 19)]